FROM golang:alpine AS builder
RUN apk add --no-cache git make
WORKDIR /src
RUN git clone https://github.com/sipeed/picoclaw.git .
RUN go mod download
RUN cp -r workspace cmd/picoclaw/workspace
RUN go build -o /go/bin/picoclaw ./cmd/picoclaw

FROM alpine:latest
RUN apk add --no-cache ca-certificates curl
COPY --from=builder /go/bin/picoclaw /usr/local/bin/picoclaw
WORKDIR /root/
COPY picoclaw/ /root/.picoclaw/
CMD ["picoclaw", "gateway"]
