FROM golang:alpine AS builder
RUN apk add --no-cache git make
WORKDIR /src
RUN git clone https://github.com/sipeed/picoclaw.git .
RUN ls -R
RUN go mod download
RUN go build -o /go/bin/picoclaw .

FROM alpine:latest
RUN apk add --no-cache ca-certificates curl
COPY --from=builder /go/bin/picoclaw /usr/local/bin/picoclaw
WORKDIR /root/
COPY picoclaw/ /root/.picoclaw/
CMD ["picoclaw", "gateway"]
